name: 'Analyse Microsoft 365 compliance results'
description: 'Github Action to analyse Microsoft 365 app compliance results'
inputs:
  report-name:
    description: 'name of the compliance report'
    required: true
  resource-list:
    description: 'list of resource ids deployed in the action'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
  